#!/bin/bash
# Extract user-typed messages from Claude Code transcripts, newer than a given epoch.
# Usage: extract-user-messages.sh <since_epoch>   → digest on stdout
# Pure/read-only: owns no state; the runner decides the window and persists it.

SINCE="${1:?usage: extract-user-messages.sh <since_epoch>}"
_LIB="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/.." 2>/dev/null && pwd)/core/lib.sh"
[ -r "$_LIB" ] || { echo "extract-user-messages: core/lib.sh not found next to this script" >&2; exit 1; }
. "$_LIB"
PROJECTS="$(mk_projects_dir)"
MAX_BYTES=300000   # defensive cap; miner also sees a truncation marker if hit

# -newermt is GNU-only: compare against a reference file stamped with the epoch instead
REF=$(mktemp); trap 'rm -f "$REF"' EXIT
ts=$(date -d "@$SINCE" +%Y%m%d%H%M.%S 2>/dev/null || date -r "$SINCE" +%Y%m%d%H%M.%S 2>/dev/null)
[ -n "$ts" ] && touch -t "$ts" "$REF"

# miner sessions run with cwd inside claude-feedback — skip their project dirs entirely
find "$PROJECTS" -mindepth 2 -maxdepth 2 -name '*.jsonl' ! -name 'agent-*.jsonl' \
     -newer "$REF" 2>/dev/null \
| grep -v 'claude-feedback' | sort \
| while IFS= read -r f; do
    proj=$(basename "$(dirname "$f")"); sess=$(basename "$f" .jsonl | cut -c1-8)
    jq -r --arg tag "$proj/$sess" --argjson since "$SINCE" '
      select(.type=="user" and ((.isMeta // false)|not))
      | (.timestamp // "") as $ts
      # per-message time filter (file mtime is too coarse for long-lived sessions)
      | select((($ts | sub("\\.[0-9]+Z$"; "Z") | try fromdateiso8601 catch 0) >= $since))
      | .message.content
      # tool_result messages are dropped as content, EXCEPT rejection events, which are
      # kept as compact markers — the act of declining is a strong preference signal
      | if type=="array" and ([.[] | select(.type=="tool_result")] | length) > 0 then
          ([.[] | select(.type=="tool_result") | .content
            | if type=="string" then . else ([.[]? | .text? // ""] | join(" ")) end
           ] | join(" ")) as $tr
          | (if ($tr | test("doesn.t want to (proceed|take this action)|rejected the tool|user rejected")) then "[user rejected a tool call]" else "" end)
        elif type=="string" then .
        else ([.[] | select(.type=="text") | .text] | join("\n")) end
      # strip injected/non-typed spans in place (a real ask can share a message with them)
      | gsub("<system-reminder>.*?</system-reminder>"; ""; "s")
      | gsub("<local-command-caveat>.*?</local-command-caveat>"; ""; "s")
      | gsub("<local-command-stdout>.*?</local-command-stdout>"; ""; "s")
      | gsub("<command-name>.*?</command-name>"; ""; "s")
      | gsub("<command-message>.*?</command-message>"; ""; "s")
      | gsub("<command-args>.*?</command-args>"; ""; "s")
      | gsub("<ide_opened_file>.*?</ide_opened_file>"; ""; "s")
      | gsub("<ide_selection>.*?</ide_selection>"; ""; "s")
      # a truncated injected block can arrive with no closing tag (seen with a
      # local-command-stdout cut mid-stream): an unclosed opener means everything
      # after it is injected noise, so cut to end-of-message, then sweep any
      # orphan tags (e.g. a closer whose opener sat inside an already-stripped span)
      | gsub("<(system-reminder|local-command-caveat|local-command-stdout|command-name|command-message|command-args|ide_opened_file|ide_selection)>.*$"; ""; "s")
      | gsub("</?(system-reminder|local-command-caveat|local-command-stdout|command-name|command-message|command-args|ide_opened_file|ide_selection)>"; "")
      | gsub("\\[Request interrupted by user[^]]*\\]"; "[user interrupted]")
      | gsub("Caveat: The messages below were generated by the user[^\n]*"; "")
      | gsub("^[[:space:]]+|[[:space:]]+$"; "")
      | select(length > 2)
      | select(test("\\[feedback-miner\\]") | not)
      | "[\($tag) \($ts)]\n\(.)\n---"
    ' "$f" 2>/dev/null
  done \
| head -c "$MAX_BYTES"
