#!/bin/bash
# Extract user-typed messages from Claude Code transcripts, newer than a given epoch.
# Usage: extract-user-messages.sh <since_epoch>   → digest on stdout
# Pure/read-only: owns no state; the runner decides the window and persists it.

SINCE="${1:?usage: extract-user-messages.sh <since_epoch>}"
PROJECTS="$HOME/.claude/projects"
MAX_BYTES=300000   # defensive cap; miner also sees a truncation marker if hit

# miner sessions run with cwd inside claude-feedback — skip their project dirs entirely
find "$PROJECTS" -mindepth 2 -maxdepth 2 -name '*.jsonl' ! -name 'agent-*.jsonl' \
     -newermt "@$SINCE" 2>/dev/null \
| grep -v 'claude-feedback' | sort \
| while IFS= read -r f; do
    proj=$(basename "$(dirname "$f")"); sess=$(basename "$f" .jsonl | cut -c1-8)
    jq -r --arg tag "$proj/$sess" --argjson since "$SINCE" '
      select(.type=="user" and ((.isMeta // false)|not))
      | (.timestamp // "") as $ts
      # per-message time filter (file mtime is too coarse for long-lived sessions)
      | select((($ts | sub("\\.[0-9]+Z$"; "Z") | try fromdateiso8601 catch 0) >= $since))
      | .message.content
      # tool_result messages are dropped as content, EXCEPT rejection events, which are
      # kept as compact markers — the act of declining is a strong preference signal
      | if type=="array" and ([.[] | select(.type=="tool_result")] | length) > 0 then
          ([.[] | select(.type=="tool_result") | .content
            | if type=="string" then . else ([.[]? | .text? // ""] | join(" ")) end
           ] | join(" ")) as $tr
          | (if ($tr | test("doesn.t want to (proceed|take this action)|rejected the tool|user rejected")) then "[user rejected a tool call]" else "" end)
        elif type=="string" then .
        else ([.[] | select(.type=="text") | .text] | join("\n")) end
      # strip injected/non-typed spans in place (a real ask can share a message with them)
      | gsub("<system-reminder>.*?</system-reminder>"; ""; "s")
      | gsub("<local-command-caveat>.*?</local-command-caveat>"; ""; "s")
      | gsub("<local-command-stdout>.*?</local-command-stdout>"; ""; "s")
      | gsub("<command-name>.*?</command-name>"; ""; "s")
      | gsub("<command-message>.*?</command-message>"; ""; "s")
      | gsub("<command-args>.*?</command-args>"; ""; "s")
      | gsub("<ide_opened_file>.*?</ide_opened_file>"; ""; "s")
      | gsub("<ide_selection>.*?</ide_selection>"; ""; "s")
      | gsub("\\[Request interrupted by user[^]]*\\]"; "[user interrupted]")
      | gsub("Caveat: The messages below were generated by the user[^\n]*"; "")
      | gsub("^[[:space:]]+|[[:space:]]+$"; "")
      | select(length > 2)
      | select(test("\\[feedback-miner\\]") | not)
      | "[\($tag) \($ts)]\n\(.)\n---"
    ' "$f" 2>/dev/null
  done \
| head -c "$MAX_BYTES"
